{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: greengate-backend
  namespace: greengate
  labels:
    app: greengate-backend
    chart: {{ include "greengate.chart" . }}
    release: monitor
    component: backend
spec:
  selector:
    matchLabels:
      app: greengate-backend
      release: greengate
  endpoints:
  - port: http
    path: {{ .Values.monitoring.serviceMonitor.path }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace | default "greengate" }}
{{- end }}